# Generated by Django 5.1.3 on 2024-11-20 14:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="usage",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="usage",
            name="value",
        ),
        migrations.AddField(
            model_name="usage",
            name="total_value",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="UsageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_products",
                        to="inventory.product",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_products",
                        to="inventory.usage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usage",
            name="products",
            field=models.ManyToManyField(
                related_name="usage_sessions",
                through="inventory.UsageProduct",
                to="inventory.product",
            ),
        ),
    ]
